config/routes.rb
Rails.application.routes.draw do
  ### creating scope :public without altering URL. 
  scope module: :public do
    root to: 'homes#top'
    resource :end_users, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]

    ## routing for cart items
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "cart_items/" => "cart_items#destroy_all", as: "destroy_all_cart_items"

    ## routing for order
    post "orders/confirm" => "orders#confirm", as: "order_confirm"
    get "orders/done" => "orders#done", as: "order_done"
    resources :orders, only: [:index, :new, :show, :create]


    ## routing for devise and controllers
    get "end_users/unregister/confirm" => "end_users#confirm", as: "end_users_unregister"
    devise_for :end_users, controllers: {sessions: "public/end_users/sessions", registrations: 'public/end_users/registrations', passwords: 'public/end_users/passwords'}
  end

  ### creating scope :admin without altering URL.
  scope module: :admin do 
    devise_for :admin, controllers: {sessions: 'admin/admin/sessions', passwords: 'admin/admin/passwords'}
  end
  # creating namespace :admin and altering url
  namespace :admin do
    get '/items/search' => 'items#search', as: :item_search
    resources :end_users, only: [:index]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :new, :create, :show]
    resources :orders, only: [:index, :show, :update]
    resource :order_details, only: [:update]
    get '/' => 'homes#top', as: :top
  end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :end_user

    def shipping_information
        "#{self.zip_code} #{self.address} #{self.recipient_name}"
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :end_user 
    belongs_to :item
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  acts_as_paranoid column: :is_unregistered


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name_kanji, :first_name_kanji, :last_name_kana, :first_name_kana, :zip_code, :address, :phone_number, presence: true

  has_many :cart_items
  has_many :orders
  has_many :addresses
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details

    attachment :image

    def self.search(search)
        return self.all unless search
        self.where(['name LIKE ?', "%#{search}%"])
    end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :end_user, -> { with_deleted }
    has_many :order_details

    Order.includes(:end_user).all

    enum preparation_status: [:pending_payment, :confirmed_payment, :producing, :shipping_prep, :shipped]
    
    enum payment_method: [:credit_card, :bank_transfer]

    def total_amount
        order_details = OrderDetail.where(order_id: self.id)
        amounts = []
        order_details.each do |detail|
            amounts.push(detail.amount)
        end
        return amounts.sum
    end

    def shipping_information
        "#{self.zip_code} #{self.address} #{self.recipient_name}"
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order 
    belongs_to :item

    enum production_status: [:unavailable, :pending_production, :producing, :produced]
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
    def index
        @users = EndUser.with_deleted
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @new_genre = Genre.new()
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    genre = Genre.new(genre_params)
    genre.is_activated = params[:is_activated]
    if genre.save
      redirect_to admin_genres_path
    else
      @new_genre = genre
      @genres = Genre.all
      render :index
    end
  end

  def update
    genre = Genre.find(params[:id])
    genre.is_activated = params[:is_activated]
    if genre.update(genre_params)
      redirect_to admin_genres_path
    else
      @genre = genre 
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :is_activated)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all()
    @genres = Genre.where(is_activated: true)
  end

  def new
    @new_item = Item.new()
    @genres = Genre.where(is_activated: true)
  end

  def show
  end

  def edit
  end

  def create
    new_item = Item.new(item_params)
    new_item.is_in_stock = params[:is_in_stock]
    if new_item.save
      redirect_to admin_item_path(new_item)
    else 
      @new_item = new_item
      @genres = Genre.where(is_activated: true)
      render :new
    end
  end

  def search
    @items = Item.search(params[:search])
    @genres = Genre.where(is_activated: true)
    render :index
  end

  private
  def item_params 
    params.require(:item).permit(:name, :description, :genre_id, :untaxed_price, :is_in_stock, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def index 
        @orders = Order.all.order(created_at: "DESC")
    end

    def show
        @order = Order.find(params[:id])
        @order_details = OrderDetail.where(order_id: @order.id)
    end

    def update
        order = Order.find(params[:id])  
        ## validation to make sure production_status for order_details only change when preparation_status changes from something else to "入金確認"
        if order.preparation_status != "confirmed_payment"
            order.update(preparation_status: order_param[:preparation_status].to_i)
            
            ## 入金確認になったら紐づくorder_detailの制作ステータスを全て制作待ちにする
            if order.preparation_status == "confirmed_payment"
                order_details = OrderDetail.where(order_id: order.id)
                order_details.each do |order_detail|
                    order_detail.update(production_status: 1)
                end
            end
        else 
            order.update(preparation_status: order_param[:preparation_status].to_i) 
        end


        redirect_to admin_order_path(order)
    end

    private
    def order_param 
        params.require(:order).permit(:preparation_status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    ### for setting up strong parameter (1)
    before_action :configure_permitted_parameters, if: :devise_controller?
    ###

    protected
    ### for setting up strong parameter (2)
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name_kanji, :first_name_kanji, :last_name_kana, :first_name_kana, :zip_code, :address, :phone_number])
    end
    ###
    
    ### redirection after sign_in/ sign_up/ sign_out
    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope.is_a?(Admin)
            admin_top_path
        else
            end_users_path
        end
    end
    def after_sign_up_path_for(resource_or_scope)
        end_users_path
    end
    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :end_user
            root_path
        else
            # new_end_user_session_path
            new_admin_session_path
        end
    end
    ###

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/end_users/index.html.erb
<div class="container">
    <h2> 会員一覧　</h2>
    <table class="enduser-index-table">
        <thead>
            <tr class="table-active enduser-index-tr">
                <th class="enduser-index-th" >会員ID</th>
                <th class="enduser-index-th" colspace="2">氏名</th>
                <th class="enduser-index-th" colspace="2">メールアドレス</th>
                <th class="enduser-index-th" colspace="2">ステータス</th>
            </tr>
            <% @users.each do |user| %>
            <tr class="enduser-index-tr">
                <td><%= user.id %></th>
                <td><%= user.last_name_kanji%><%= user.first_name_kanji%></th>
                <td><%= user.email %></th>
                <% if !user.is_unregistered %>
                    <td>有効</th>
                <% else %>
                    <td>退会済</th>
                <% end %>
            </tr>
            <%end%>
            
        </thead>
    </table>

</div>

app/views/admin/genres/edit.html.erb
<div class="container">
    <h2>ジャンル一覧・追加</h2>
    <%= form_with model: @genre, url: admin_genre_path do |f|%>
    <table class="admin-genre-table-form">
        <tbody>
            <tr>
                <td class="admin-genre-td-form"><strong>ジャンル</strong></td>
                <td class="admin-genre-td-form"><%= f.text_field :name%></td>
                <% if @genre.is_activated %>
                    <td class="admin-genre-td-form"><%= radio_button_tag(:is_activated, "true", :checked) %> 有効</td>
                    <td class="admin-genre-td-form"><%= radio_button_tag(:is_activated, "false") %> 無効</td>
                <%else%>
                    <td class="admin-genre-td-form"><%= radio_button_tag(:is_activated, "true") %> 有効</td>
                    <td class="admin-genre-td-form"><%= radio_button_tag(:is_activated, "false", :checked) %> 無効</td>
                <%end%>

                <td class="admin-genre-td-form"><%= f.submit "追加", class: "btn btn-primary" %></td>
            </td>
        </tbody>
    </table>
    <%end%>                
</div>

app/views/admin/genres/index.html.erb
<div class="container">
    <h2>ジャンル一覧・追加</h2>
    <%= form_with model: @new_genre, url: admin_genres_path do |f|%>
    <table class="admin-genre-table-form">
        <tbody>
            <tr>
                <td class="admin-genre-td-form"><strong>ジャンル</strong></td>
                <td class="admin-genre-td-form"><%= f.text_field :name%></td>
                <td class="admin-genre-td-form"><%= radio_button_tag(:is_activated, "true") %> 有効</td>
                <td class="admin-genre-td-form"><%= radio_button_tag(:is_activated, "false") %> 無効</td>
                <td class="admin-genre-td-form"><%= f.submit "追加", class: "btn btn-primary" %></td>
            </td>
        </tbody>
    </table>
    <%end%>

    <table class="admin-genre-table">
        <thead>
            <tr class="table-active">
                <th>ジャンル</th>
                <th colspan="2">状態</th>

            </tr>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
            <tr>
                <td class="admin-genre-td"><%= genre.name %></td>
                <% if genre.is_activated %>
                    <td class="admin-genre-td">有効</td>
                <%else%>
                    <td class="admin-genre-td">無効</td>
                <%end%>
                <td class="admin-genre-td"><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-primary"%></td>
            </tr>
        <%end%>
                
</div>

app/views/admin/homes/top.html.erb
<h2>Adminトップページ</h2>

app/views/admin/items/index.html.erb
<div class="container">
    <h2>商品一覧</h2>
    <div class="d-flex flex-row-reverse">
        <%= link_to "+", new_admin_item_path, class: "btn pmd-btn-fab pmd-ripple-effect btn-primary "%>
    </div>
    <table class="admin-items-table">
        <thead>
            <tr class="table-active">
                <th class="admin-items-th">商品ID</th>
                <th class="admin-items-th">商品名</th>
                <th class="admin-items-th">税抜き価格</th>
                <th class="admin-items-th">ジャンル</th>
                <th class="admin-items-th">ステータス</th>
            </tr>
        </thead>
        <tbody>
            <% @items.each do |item| %>
                <tr>
                    <td class="admin-items-td"><%= item.id %></td>
                    <td class="admin-items-td"><%= item.name %></td>
                    <td class="admin-items-td"><%= item.untaxed_price %> </td>
                    <td class="admin-items-td"><%= @genres.find(item.genre_id).name %></td>
                    <td class="admin-items-td">
                        <% if item.is_in_stock %>
                        販売中
                        <%else%>
                        販売停止中
                        <%end%>
                    </td>
                </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/admin/items/new.html.erb
<div class="container">
    <%= form_with model: @new_item, url: admin_items_path do |f| %>
    <table>
        <tbody>
            <tr>
                <td><%= f.attachment_field :image %></td>
                <td>
                    <table>
                        <tbody>
                            <tr>
                                <td><%= f.label "商品名" %></td>
                                <td><%= f.text_field :name %></td>
                            </tr>
                            <tr>
                                <td><%= f.label "商品説明" %></td>
                                <td><%= f.text_area :description %></td>
                            </tr>
                            <tr>
                                <td><%= f.label "ジャンル" %></td>
                                <td><%= f.collection_select(:genre_id, @genres, :id, :name, include_blank: :true)%>
                            </tr>
                            <tr>
                                <td><%= f.label "税抜き価格" %></td>
                                <td><%= f.number_field :untaxed_price %>円</td>
                            </tr>
                            <tr>
                                <td><%= f.label "販売ステータス"%></td>
                                <td><%= select_tag(:is_in_stock, options_for_select([['販売中', true], ["販売停止中", false]])) %>
                        </tbody>
                    </table>
                </td>
        </tbody>
    </table>
    <div class="d-flex flex-row-reverse">
        <%= f.submit "新規登録", class: "btn btn-primary p-2"%>
    </div>
    <%end%>
</div>

app/views/admin/items/show.html.erb
<h1>Admin::Items#show</h1>
<p>Find me in app/views/admin/items/show.html.erb</p>

app/views/admin/orders/index.html.erb
<div class="container">
    <h2 class="margin-tb">注文履歴一覧</h2>
    <table>
        <thead>
            <tr class="table-active admin-order-index-tr">
                <th>購入日時</th>
                <th>購入者</th>
                <th>注文個数</th>
                <th>注文ステータス</th>
            </tr>
        </thead>
        <tbody>
            <% @orders.each do |order| %>
            <tr class="admin-order-index-tr">
                <td class="admin-order-index-td">
                    <%= link_to admin_order_path(order) do %>
                        <%= l order.created_at %>
                    <%end%>
                </td>
                <td class="admin-order-index-td">
                    <%= order.end_user.last_name_kanji %><%= order.end_user.first_name_kanji %>
                </td>
                <td class="admin-order-index-td">
                    <%= order.total_amount %>
                </td>
                <td class="admin-order-index-td">
                    <%= order.preparation_status_i18n %>
                </td>
            </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
    <h2>注文履歴詳細</h2>
    <table>
        <tbody>
            <tr>
                <td><h5>購入者</h5></td>
                <td><%= @order.end_user.last_name_kanji %> <%= @order.end_user.first_name_kanji%></td>
            </tr>
            <tr>
                <td><h5>配送先</h5></td>
                <td><%= @order.shipping_information %></td>
            </tr>
            <tr>
                <td><h5>支払方法</h5></td>
                <td><%= @order.payment_method_i18n %></td>
            </tr>

            <tr>
                <td><h5>注文ステータス</h5></td>
                <td>
                <%= form_with model: @order, url: admin_order_path(@order) do |f|%>

                    <%= f.select :preparation_status, Order.preparation_statuses.keys.map {|k| [Order.preparation_statuses_i18n[k], Order.preparation_statuses[k]]}, :selected => Order.preparation_statuses[@order.preparation_status] %>
                
                    <%= f.submit "更新", class: "btn btn-primary" %>
                <%end%>
                </td>
            </tr>

        </tbody>
    </table>

    <div class="row">

        <table class="margin-tb col-8">
            <thead>
                <tr class="table-active admin-order-show-tr">
                    <th>商品名</th>
                    <th>単価（税込み）</th>
                    <th>数量</th>
                    <th>小計</th>
                    <th>制作ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @order_details.each do |order_detail| %>
                <tr>
                    <td class="admin-order-show-td"><%= order_detail.item.name %></td>
                    <td class="admin-order-show-td"><%= order_detail.taxed_price %></td>
                    <td class="admin-order-show-td"><%= order_detail.amount%></td>
                    <td class="admin-order-show-td"><%= order_detail.taxed_price * order_detail.amount %></td>
                    <td class="admin-order-show-td">
                        <%= form_with model: order_detail, url: admin_order_details_path(@order) do |f|%> 
                            <%= f.select :production_status, OrderDetail.production_statuses.keys.map{ |k| [OrderDetail.production_statuses_i18n[k], OrderDetail.production_statuses[k]]}, :selected => OrderDetail.production_statuses[order_detail.production_status] %>
                            <%= f.hidden_field :id, value: order_detail.id %>
                            <%= f.submit "更新", class: "btn btn-primary"%>
                        <%end%>
                    </td>
                </tr>
                <%end%>
            </tbody>
        </table>
        <table class="col-4">
            <tbody>
                <tr>
                    <td><h5>商品合計</h5></td>
                    <td> <%= @order.total_price %> </td>
                </tr>
                <tr>
                    <td><h5>送料</h5></td>
                    <td><%= @order.shipping_fee %> </td>
                </tr>
                <tr>
                    <td><h5>請求金額合計</h5></td>
                    <td><h6><%= @order.total_price + @order.shipping_fee %></h6></td>
                <tr>
            </tbody>
    </div>
</div>
        