config/routes.rb
Rails.application.routes.draw do
  ### creating scope :public without altering URL. 
  scope module: :public do
    root to: 'homes#top'
    resource :end_users, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]

    ## routing for cart items
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "cart_items/" => "cart_items#destroy_all", as: "destroy_all_cart_items"

    ## routing for order
    post "orders/confirm" => "orders#confirm", as: "order_confirm"
    get "orders/done" => "orders#done", as: "order_done"
    resources :orders, only: [:index, :new, :show, :create]


    ## routing for devise and controllers
    get "end_users/unregister/confirm" => "end_users#confirm", as: "end_users_unregister"
    devise_for :end_users, controllers: {sessions: "public/end_users/sessions", registrations: 'public/end_users/registrations', passwords: 'public/end_users/passwords'}
  end

  ### creating scope :admin without altering URL.
  scope module: :admin do 
    devise_for :admin, controllers: {sessions: 'admin/admin/sessions', passwords: 'admin/admin/passwords'}
  end
  # creating namespace :admin and altering url
  namespace :admin do
    get '/items/search' => 'items#search', as: :item_search
    resources :end_users, only: [:index]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :new, :create, :show]
    resources :orders, only: [:index, :show, :update]
    resource :order_details, only: [:update]
    get '/' => 'homes#top', as: :top
  end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :end_user

    def shipping_information
        "#{self.zip_code} #{self.address} #{self.recipient_name}"
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :end_user 
    belongs_to :item
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  acts_as_paranoid column: :is_unregistered


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name_kanji, :first_name_kanji, :last_name_kana, :first_name_kana, :zip_code, :address, :phone_number, presence: true

  has_many :cart_items
  has_many :orders
  has_many :addresses
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details

    attachment :image

    def self.search(search)
        return self.all unless search
        self.where(['name LIKE ?', "%#{search}%"])
    end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :end_user, -> { with_deleted }
    has_many :order_details

    Order.includes(:end_user).all

    enum preparation_status: [:pending_payment, :confirmed_payment, :producing, :shipping_prep, :shipped]
    
    enum payment_method: [:credit_card, :bank_transfer]

    def total_amount
        order_details = OrderDetail.where(order_id: self.id)
        amounts = []
        order_details.each do |detail|
            amounts.push(detail.amount)
        end
        return amounts.sum
    end

    def shipping_information
        "#{self.zip_code} #{self.address} #{self.recipient_name}"
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order 
    belongs_to :item

    enum production_status: [:unavailable, :pending_production, :producing, :produced]
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all()
    @genres = Genre.where(is_activated: true)
  end

  def new
    @new_item = Item.new()
    @genres = Genre.where(is_activated: true)
  end

  def show
  end

  def edit
  end

  def create
    new_item = Item.new(item_params)
    new_item.is_in_stock = params[:is_in_stock]
    if new_item.save
      redirect_to admin_item_path(new_item)
    else 
      @new_item = new_item
      @genres = Genre.where(is_activated: true)
      render :new
    end
  end

  def search
    @items = Item.search(params[:search])
    @genres = Genre.where(is_activated: true)
    render :index
  end

  private
  def item_params 
    params.require(:item).permit(:name, :description, :genre_id, :untaxed_price, :is_in_stock, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    ### for setting up strong parameter (1)
    before_action :configure_permitted_parameters, if: :devise_controller?
    ###

    protected
    ### for setting up strong parameter (2)
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name_kanji, :first_name_kanji, :last_name_kana, :first_name_kana, :zip_code, :address, :phone_number])
    end
    ###
    
    ### redirection after sign_in/ sign_up/ sign_out
    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope.is_a?(Admin)
            admin_top_path
        else
            end_users_path
        end
    end
    def after_sign_up_path_for(resource_or_scope)
        end_users_path
    end
    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :end_user
            root_path
        else
            # new_end_user_session_path
            new_admin_session_path
        end
    end
    ###

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/c747c50be4.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if !admin_signed_in? %>
    <%= link_to "Nagano Cake", root_path, class: "navbar-brand"%>
  <%else%>
    <%= link_to "管理者 Nagano Cake", admin_top_path, class: "navbar-brand"%>
  <%end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
    <% if !end_user_signed_in? && !admin_signed_in? %>
      <li class="nav-item">
        <%= link_to "商品一覧", items_path, class: "nav-link"%> 
      </li>
      <li class="nav-item">
        <%= link_to "新規登録", new_end_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item'">
        <%= link_to "ログイン", new_end_user_session_path, class: "nav-link" %>
      </li>
    <% elsif end_user_signed_in? %>
      <li class="nav-item">
        ようこそ, <%= current_end_user.last_name_kanji %> さん!
      </li>
      <li class="nav-item">
        <%= link_to "マイページ", end_users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "商品一覧", items_path, class: "nav-link"%> 
      </li>
      <li class="nav-item">
        <%= link_to "カート", cart_items_path, class: "nav-link"%> 
      </li>
      <li class="nav-item'">
        <%= link_to "ログアウト", destroy_end_user_session_path, class: "nav-link", method: :delete %>
      </li> 
    <% else %>
      <li class="nav-item">
       <%= link_to "商品一覧", admin_items_path, class: "nav-link"%> 
      </li>
      <li class="nav-item">
       <%= link_to "会員一覧", admin_end_users_path, class: "nav-link"%> 
      </li>
      <li class="nav-item">
       <%= link_to "注文一覧", admin_orders_path, class: "nav-link"%> 
      </li>
      <li class="nav-item">
        <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link"%>  
      </li>
      <li class="nav-item'">
        <%= link_to "ログアウト", destroy_admin_session_path, class: "nav-link", method: :delete %>
      </li> 
    </ul>
      <%= form_tag(admin_item_search_path, :method => 'get') do%>
        <%= text_field_tag :search%>
        <%= button_tag type: "submit", class: "btn" do %>
          <i class="fas fa-search"></i>
        <%end%>
      <%end%>
    <%end%>
  </div>
</nav>

    <%= yield %>
  </body>
</html>